spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:delivery}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:secret}

  application:
    name: delivery